version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: tasks
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: ['tar.gz']
    format_overrides:
      - goos: windows
        formats: ['zip']

    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    files:
      - README.md
      - LICENSE
      - fish/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^refactor:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: vrischmann
    name: tasks
  name_template: "{{ .ProjectName }} v{{ .Version }}"
  draft: false
  prerelease: auto
