version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: tasks
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - demo.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^refactor:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: vrischmann
    name: tasks
  name_template: "{{ .ProjectName }} v{{ .Version }}"
  draft: false
  prerelease: auto

brews:
  - name: tasks
    repository:
      owner: vrischmann
      name: homebrew-tap
      branch: main
    homepage: "https://github.com/vrischmann/tasks"
    description: "Terminal-based markdown task manager"
    license: "MIT"
    install: |
      bin.install "tasks"
    test: |
      system "#{bin}/tasks", "--version"
